#!/bin/bash

folder=${1:-"test_cases"}
slow=${2:-0}
it=${3:-100}

for net in fc5
do
	echo Evaluating network ${net}...
	for spec in `ls ../$folder/${net}`
	do
		if [[ "$spec" == *"perturbed"* ]] || [[ "$spec" == *"details"* ]]
		then
			:
		else
			python3 verifier.py --net ${net} --spec ../$folder/${net}/${spec} --slow $slow --it $it
		fi
	done
done
